# Generated by Django 3.1.6 on 2021-02-17 14:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=datetime.date(2021, 2, 17)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='time',
            field=models.TimeField(auto_now_add=True, default='14:12:51'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=datetime.date(2021, 2, 17)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='time',
            field=models.TimeField(auto_now_add=True, default='14:13:16'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LikeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='likes',
            field=models.ManyToManyField(blank=True, to='api.LikeModel'),
        ),
        migrations.AddField(
            model_name='commentmodel',
            name='likes',
            field=models.ManyToManyField(blank=True, to='api.LikeModel'),
        ),
    ]
