# Generated by Django 3.1.6 on 2021-02-25 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210224_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='time',
            new_name='time_created',
        ),
        migrations.RenameField(
            model_name='commentmodel',
            old_name='time',
            new_name='time_created',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 2, 25, 10, 21, 43, 8603)),
            preserve_default=False,
        ),
    ]
